EDA Analysis

In [72]:
import pandas as pd
import numpy as np

In [78]:
#creat a reference table that includes population, cripes per x people, avg house price per reigon

population = [1188090, 1175364, 669380, 15111, 1248649]
avg_property_price = [214393, 712600, 343282, 934788, 584320]
labels = ["Nottinghamshire Police","Leicestershire Police","Gloucestershire Constabulary","City of London Police","Surrey Police"]

reference_df = pd.DataFrame({
    "Population": population,
    "Avg house price": avg_property_price
}, index=labels)

reference_df

                              Population  Avg house price
Nottinghamshire Police           1188090           214393
Leicestershire Police            1175364           712600
Gloucestershire Constabulary      669380           343282
City of London Police              15111           934788
Surrey Police                    1248649           584320

In [79]:
#import clean data
path = r"C:\Users\melpa\OneDrive\My Documents\Crime Analysis Project\data\processed\Clean_street_analysis.csv"
df=pd.read_csv(path)

In [80]:
#number of crimes per area
number_of_crimes = df['Falls within'].value_counts()

In [81]:
reference_df["Crime count"] = number_of_crimes

In [82]:
#workong out crimes per 1000 people to standardise comparisosn
reference_df['Crime_per_1000'] = (reference_df['Crime count']/reference_df['Population']) * 1000
reference_df

,Population,Avg house price,Crime count,Crime_per_1000
Nottinghamshire Police,1188090,214393,240330,202.282655
Leicestershire Police,1175364,712600,215503,183.350009
Gloucestershire Constabulary,669380,343282,115276,172.213093
City of London Police,15111,934788,19403,1284.031500
Surrey Police,1248649,584320,175447,140.509463

In [64]:
number_of_crimes

Falls within
Nottinghamshire Police          240330
Leicestershire Police           215503
Surrey Police                   175447
Gloucestershire Constabulary    115276
City of London Police            19403
Name: count, dtype: int64